services:
  - type: web
    name: webvibes-backend
    env: java
    region: singapore
    plan: free
    buildCommand: cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -jar target/portal-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 10000
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
